# Generated by Django 6.0.6 on 2026-07-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle Matrícula', 'verbose_name_plural': 'Detalle Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
